#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pulsus.SharePoint.Core
{
    using System;
    using System.Collections.Generic;
    
    #line 2 "..\..\Core\LoggingEventTemplate.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 3 "..\..\Core\LoggingEventTemplate.cshtml"
    using Pulsus.SharePoint.Core;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class LoggingEventTemplate : RazorTemplateBase<LoggingEventTemplateModel>
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");




WriteLiteral("\r\n<table cellpadding=\"0\" cellspacing=\"0\" class=\"title\">\r\n    <tr>\r\n        <td wi" +
"dth=\"8\" style=\"\" class=\"first-col level ");


            
            #line 8 "..\..\Core\LoggingEventTemplate.cshtml"
                                                 Write(Model.LevelClass);

            
            #line default
            #line hidden
WriteLiteral("\">&nbsp;</td>\r\n        <td><h1>");


            
            #line 9 "..\..\Core\LoggingEventTemplate.cshtml"
           Write(Model.GetFormattedTitle());

            
            #line default
            #line hidden
WriteLiteral("</h1></td>\r\n    </tr>\r\n</table>\r\n    \r\n<h2>General</h2>\r\n<table cellpadding=\"0\" c" +
"ellspacing=\"0\">\r\n    <tr>\r\n        <td class=\"first-col\">Date</td>\r\n        <td>" +
"");


            
            #line 17 "..\..\Core\LoggingEventTemplate.cshtml"
       Write(Model.LoggingEvent.Date);

            
            #line default
            #line hidden
WriteLiteral(" UTC</td>\r\n    </tr>\r\n    <tr class=\"alt\">\r\n        <td class=\"first-col\">LogKey<" +
"/td>\r\n        <td>");


            
            #line 21 "..\..\Core\LoggingEventTemplate.cshtml"
       Write(Model.LoggingEvent.LogKey);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n    </tr>\r\n");


            
            #line 23 "..\..\Core\LoggingEventTemplate.cshtml"
     if (!Model.LoggingEvent.ApiKey.IsNullOrEmpty()) {

            
            #line default
            #line hidden
WriteLiteral("        <tr>\r\n            <td class=\"first-col\">ApiKey</td>\r\n            <td>");


            
            #line 26 "..\..\Core\LoggingEventTemplate.cshtml"
           Write(Model.LoggingEvent.ApiKey);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n        </tr>\r\n");


            
            #line 28 "..\..\Core\LoggingEventTemplate.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <tr class=\"alt\">\r\n        <td class=\"first-col\">ID</td>\r\n        <td>");


            
            #line 31 "..\..\Core\LoggingEventTemplate.cshtml"
       Write(Model.LoggingEvent.EventId);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n    </tr>\r\n    <tr>\r\n        <td class=\"first-col\">Level</td>\r\n        <td" +
">");


            
            #line 35 "..\..\Core\LoggingEventTemplate.cshtml"
       Write(Model.LevelText);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n    </tr>\r\n    <tr class=\"alt\">\r\n        <td class=\"first-col\">User</td>\r\n" +
"        <td>");


            
            #line 39 "..\..\Core\LoggingEventTemplate.cshtml"
        Write(Model.LoggingEvent.User ?? "(none)");

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n    </tr>\r\n    <tr>\r\n        <td class=\"first-col\">Tags</td>\r\n        <td>" +
"");


            
            #line 43 "..\..\Core\LoggingEventTemplate.cshtml"
       Write(string.Join(" ", Model.LoggingEvent.Tags.ToArray()));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n    </tr>\r\n    <tr class=\"alt\">\r\n        <td class=\"first-col\">MachineName" +
"</td>\r\n        <td>");


            
            #line 47 "..\..\Core\LoggingEventTemplate.cshtml"
       Write(Model.LoggingEvent.MachineName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n    </tr>\r\n");


            
            #line 49 "..\..\Core\LoggingEventTemplate.cshtml"
     if (!Model.LoggingEvent.Psid.IsNullOrEmpty()) {

            
            #line default
            #line hidden
WriteLiteral("        <tr>\r\n            <td class=\"first-col\"><abbr title=\"Session ID\">PSID</ab" +
"br></td>\r\n            <td>");


            
            #line 52 "..\..\Core\LoggingEventTemplate.cshtml"
           Write(Model.LoggingEvent.Psid);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n        </tr>\r\n");


            
            #line 54 "..\..\Core\LoggingEventTemplate.cshtml"
    }

            
            #line default
            #line hidden

            
            #line 55 "..\..\Core\LoggingEventTemplate.cshtml"
     if (!Model.LoggingEvent.Ppid.IsNullOrEmpty()) {

            
            #line default
            #line hidden
WriteLiteral("        <tr class=\"alt\">\r\n            <td class=\"first-col\"><abbr title=\"Persiste" +
"nt Session ID\">PPID</abbr></td>\r\n            <td>");


            
            #line 58 "..\..\Core\LoggingEventTemplate.cshtml"
           Write(Model.LoggingEvent.Ppid);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n        </tr>\r\n");


            
            #line 60 "..\..\Core\LoggingEventTemplate.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</table>\r\n        \r\n");


            
            #line 63 "..\..\Core\LoggingEventTemplate.cshtml"
 if (Model.CustomData != null) {

            
            #line default
            #line hidden
WriteLiteral("    <h2>Custom Data</h2>\r\n");


            
            #line 65 "..\..\Core\LoggingEventTemplate.cshtml"
    
            
            #line default
            #line hidden
            
            #line 65 "..\..\Core\LoggingEventTemplate.cshtml"
Write(WriteTable(Model.CustomData));

            
            #line default
            #line hidden
            
            #line 65 "..\..\Core\LoggingEventTemplate.cshtml"
                                 
}

            
            #line default
            #line hidden
WriteLiteral("    \r\n");


            
            #line 68 "..\..\Core\LoggingEventTemplate.cshtml"
 if (Model.HttpContextInformation != null) {

            
            #line default
            #line hidden
WriteLiteral("    <h2>Request</h2>\r\n");



WriteLiteral("    <table cellpadding=\"0\" cellspacing=\"0\">\r\n        <tr>\r\n            <td class=" +
"\"first-col\">URL</td>\r\n            <td><a href=\"");


            
            #line 73 "..\..\Core\LoggingEventTemplate.cshtml"
                    Write(Model.HttpContextInformation.Url);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 73 "..\..\Core\LoggingEventTemplate.cshtml"
                                                       Write(Model.HttpContextInformation.Url);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n        </tr>\r\n        <tr class=\"alt\">\r\n            <td class=\"first-" +
"col\">Method</td>\r\n            <td>");


            
            #line 77 "..\..\Core\LoggingEventTemplate.cshtml"
           Write(Model.HttpContextInformation.Method);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n        </tr>\r\n        <tr>\r\n            <td class=\"first-col\">Host</td>\r\n" +
"            <td>");


            
            #line 81 "..\..\Core\LoggingEventTemplate.cshtml"
           Write(Model.HttpContextInformation.Host);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n        </tr>\r\n        <tr class=\"alt\">\r\n            <td class=\"first-col\"" +
">Referer</td>\r\n            <td>");


            
            #line 85 "..\..\Core\LoggingEventTemplate.cshtml"
           Write(Model.HttpContextInformation.Referer);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n        </tr>\r\n        <tr>\r\n            <td class=\"first-col\">IP Address<" +
"/td>\r\n            <td>");


            
            #line 89 "..\..\Core\LoggingEventTemplate.cshtml"
           Write(Model.GetFormattedIpAddress(Model.HttpContextInformation.IpAddress));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n        </tr>\r\n        <tr class=\"alt\">\r\n            <td class=\"first-col\"" +
">User Agent</td>\r\n            <td>");


            
            #line 93 "..\..\Core\LoggingEventTemplate.cshtml"
           Write(Model.GetFormattedUserAgent(Model.HttpContextInformation.UserAgent));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n        </tr>\r\n    </table>\r\n");


            
            #line 96 "..\..\Core\LoggingEventTemplate.cshtml"
      
    if (Model.HttpContextInformation.RouteValues != null) {

            
            #line default
            #line hidden
WriteLiteral("        <h2>Route Values</h2>\r\n");


            
            #line 99 "..\..\Core\LoggingEventTemplate.cshtml"
        
            
            #line default
            #line hidden
            
            #line 99 "..\..\Core\LoggingEventTemplate.cshtml"
   Write(WriteTable(Model.HttpContextInformation.RouteValues));

            
            #line default
            #line hidden
            
            #line 99 "..\..\Core\LoggingEventTemplate.cshtml"
                                                             
    }
     
    if (Model.HttpContextInformation.QueryString != null) {

            
            #line default
            #line hidden
WriteLiteral("        <h2>QueryString</h2>\r\n");


            
            #line 104 "..\..\Core\LoggingEventTemplate.cshtml"
        
            
            #line default
            #line hidden
            
            #line 104 "..\..\Core\LoggingEventTemplate.cshtml"
   Write(WriteTable(Model.HttpContextInformation.QueryString));

            
            #line default
            #line hidden
            
            #line 104 "..\..\Core\LoggingEventTemplate.cshtml"
                                                             
    }
        
    if (Model.HttpContextInformation.PostedValues != null) {

            
            #line default
            #line hidden
WriteLiteral("        <h2>Posted Values</h2>\r\n");


            
            #line 109 "..\..\Core\LoggingEventTemplate.cshtml"
        
            
            #line default
            #line hidden
            
            #line 109 "..\..\Core\LoggingEventTemplate.cshtml"
   Write(WriteTable(Model.HttpContextInformation.PostedValues));

            
            #line default
            #line hidden
            
            #line 109 "..\..\Core\LoggingEventTemplate.cshtml"
                                                              
    }
        
    if (Model.HttpContextInformation.PostedFiles != null) {

            
            #line default
            #line hidden
WriteLiteral("        <h2>Posted Files</h2>\r\n");



WriteLiteral("        <table cellpadding=\"0\" cellspacing=\"0\">\r\n            <tr>\r\n              " +
"  <th class=\"first-col\" align=\"left\">Name</th>\r\n                <th align=\"left\"" +
">Content Type</th>\r\n                <th align=\"left\">Size</th>\r\n            </tr" +
">\r\n");


            
            #line 120 "..\..\Core\LoggingEventTemplate.cshtml"
               var i = 0;  

            
            #line default
            #line hidden

            
            #line 121 "..\..\Core\LoggingEventTemplate.cshtml"
             foreach (var postedFile in Model.HttpContextInformation.PostedFiles) {
                var classAtt = i % 2 > 0 ? "class=\"alt\"" : string.Empty;

            
            #line default
            #line hidden
WriteLiteral("                <tr ");


            
            #line 123 "..\..\Core\LoggingEventTemplate.cshtml"
               Write(classAtt);

            
            #line default
            #line hidden
WriteLiteral(">\r\n                    <td class=\"first-col\">");


            
            #line 124 "..\..\Core\LoggingEventTemplate.cshtml"
                                     Write(postedFile.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");


            
            #line 125 "..\..\Core\LoggingEventTemplate.cshtml"
                   Write(postedFile.ContentType);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");


            
            #line 126 "..\..\Core\LoggingEventTemplate.cshtml"
                   Write(FileSizeFormatProvider.FileSize(postedFile.ContentLength));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n");


            
            #line 128 "..\..\Core\LoggingEventTemplate.cshtml"
                i++;
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n");


            
            #line 131 "..\..\Core\LoggingEventTemplate.cshtml"
    }
        
    if (Model.HttpContextInformation.Cookies != null) {

            
            #line default
            #line hidden
WriteLiteral("        <h2>Cookies</h2>\r\n");


            
            #line 135 "..\..\Core\LoggingEventTemplate.cshtml"
        
            
            #line default
            #line hidden
            
            #line 135 "..\..\Core\LoggingEventTemplate.cshtml"
   Write(WriteTable(Model.HttpContextInformation.Cookies));

            
            #line default
            #line hidden
            
            #line 135 "..\..\Core\LoggingEventTemplate.cshtml"
                                                         
    }
        
    if (Model.HttpContextInformation.Headers != null) {

            
            #line default
            #line hidden
WriteLiteral("        <h2>Headers</h2>\r\n");


            
            #line 140 "..\..\Core\LoggingEventTemplate.cshtml"
        
            
            #line default
            #line hidden
            
            #line 140 "..\..\Core\LoggingEventTemplate.cshtml"
   Write(WriteTable(Model.HttpContextInformation.Headers));

            
            #line default
            #line hidden
            
            #line 140 "..\..\Core\LoggingEventTemplate.cshtml"
                                                         
    }
        
    if (Model.HttpContextInformation.ServerVariables != null) {

            
            #line default
            #line hidden
WriteLiteral("        <h2>Server Variables</h2>\r\n");


            
            #line 145 "..\..\Core\LoggingEventTemplate.cshtml"
        
            
            #line default
            #line hidden
            
            #line 145 "..\..\Core\LoggingEventTemplate.cshtml"
   Write(WriteTable(Model.HttpContextInformation.ServerVariables));

            
            #line default
            #line hidden
            
            #line 145 "..\..\Core\LoggingEventTemplate.cshtml"
                                                                 
    }
        
    if (Model.HttpContextInformation.Session != null) {

            
            #line default
            #line hidden
WriteLiteral("        <h2>Session Variables</h2>\r\n");


            
            #line 150 "..\..\Core\LoggingEventTemplate.cshtml"
        
            
            #line default
            #line hidden
            
            #line 150 "..\..\Core\LoggingEventTemplate.cshtml"
   Write(WriteTable(Model.HttpContextInformation.Session));

            
            #line default
            #line hidden
            
            #line 150 "..\..\Core\LoggingEventTemplate.cshtml"
                                                         
    }
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 154 "..\..\Core\LoggingEventTemplate.cshtml"
 if (Model.ExceptionInformation != null) {

            
            #line default
            #line hidden
WriteLiteral("    <h2>Exception</h2>\r\n");



WriteLiteral("    <table cellpadding=\"0\" cellspacing=\"0\">\r\n        <tr>\r\n            <td class=" +
"\"first-col\">Message</td>\r\n            <td>");


            
            #line 159 "..\..\Core\LoggingEventTemplate.cshtml"
           Write(Model.ExceptionInformation.Message);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n        </tr>\r\n        <tr class=\"alt\">\r\n            <td class=\"first-col\"" +
">Type</td>\r\n            <td>");


            
            #line 163 "..\..\Core\LoggingEventTemplate.cshtml"
           Write(Model.ExceptionInformation.Type);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n        </tr>\r\n        <tr>\r\n            <td class=\"first-col\">Source</td>" +
"\r\n            <td>");


            
            #line 167 "..\..\Core\LoggingEventTemplate.cshtml"
           Write(Model.ExceptionInformation.Source);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n        </tr>\r\n        <tr class=\"alt\">\r\n            <td class=\"first-col\"" +
">StatusCode</td>\r\n            <td>");


            
            #line 171 "..\..\Core\LoggingEventTemplate.cshtml"
           Write(Model.ExceptionInformation.StatusCode);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n        </tr>\r\n    </table>\r\n");


            
            #line 174 "..\..\Core\LoggingEventTemplate.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("    \r\n");


            
            #line 176 "..\..\Core\LoggingEventTemplate.cshtml"
 if (Model.StackTrace != null) {

            
            #line default
            #line hidden
WriteLiteral("    <h2>StackTrace</h2>\r\n");



WriteLiteral("    <pre class=\"stacktrace\">");


            
            #line 178 "..\..\Core\LoggingEventTemplate.cshtml"
                       Write(Model.StackTrace);

            
            #line default
            #line hidden
WriteLiteral("</pre>\r\n");


            
            #line 179 "..\..\Core\LoggingEventTemplate.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("    \r\n");


            
            #line 181 "..\..\Core\LoggingEventTemplate.cshtml"
 if (Model.SqlInformation != null) {

            
            #line default
            #line hidden
WriteLiteral("    <h2>SQL</h2>\r\n");


            
            #line 183 "..\..\Core\LoggingEventTemplate.cshtml"
    
            
            #line default
            #line hidden
            
            #line 183 "..\..\Core\LoggingEventTemplate.cshtml"
Write(WriteTable(Model.SqlInformation.Parameters));

            
            #line default
            #line hidden
            
            #line 183 "..\..\Core\LoggingEventTemplate.cshtml"
                                                

            
            #line default
            #line hidden
WriteLiteral("    <pre class=\"sql\">");


            
            #line 184 "..\..\Core\LoggingEventTemplate.cshtml"
                Write(Model.SqlInformation.SQL);

            
            #line default
            #line hidden
WriteLiteral("</pre>\r\n");


            
            #line 185 "..\..\Core\LoggingEventTemplate.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<br />\r\n");


            
            #line 187 "..\..\Core\LoggingEventTemplate.cshtml"
Write(Model.Footer);

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
