#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pulsus.SharePoint.Core
{
    using System;
    using System.Collections.Generic;
    
    #line 2 "..\..\Core\LoggingEventTemplate.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 3 "..\..\Core\LoggingEventTemplate.cshtml"
    using Pulsus.SharePoint.Core;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class LoggingEventTemplate : RazorTemplateBase<LoggingEventTemplateModel>
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");




WriteLiteral("\r\n<table cellpadding=\"0\" cellspacing=\"0\" class=\"title\">\r\n    <tr>\r\n        <td wi" +
"dth=\"8\" style=\"\" class=\"first-col level ");


            
            #line 8 "..\..\Core\LoggingEventTemplate.cshtml"
                                                 Write(Model.LevelClass);

            
            #line default
            #line hidden
WriteLiteral("\">&nbsp;</td>\r\n        <td><h1>");


            
            #line 9 "..\..\Core\LoggingEventTemplate.cshtml"
           Write(Model.GetFormattedTitle());

            
            #line default
            #line hidden
WriteLiteral("</h1></td>\r\n    </tr>\r\n</table>\r\n    \r\n<h2>General</h2>\r\n");


            
            #line 14 "..\..\Core\LoggingEventTemplate.cshtml"
Write(WriteTable(Model.GeneralSection));

            
            #line default
            #line hidden
WriteLiteral("\r\n        \r\n");


            
            #line 16 "..\..\Core\LoggingEventTemplate.cshtml"
 if (Model.CustomData != null) {

            
            #line default
            #line hidden
WriteLiteral("    <h2>Custom Data</h2>\r\n");


            
            #line 18 "..\..\Core\LoggingEventTemplate.cshtml"
    
            
            #line default
            #line hidden
            
            #line 18 "..\..\Core\LoggingEventTemplate.cshtml"
Write(WriteTable(Model.CustomData));

            
            #line default
            #line hidden
            
            #line 18 "..\..\Core\LoggingEventTemplate.cshtml"
                                 
}

            
            #line default
            #line hidden
WriteLiteral("    \r\n");


            
            #line 21 "..\..\Core\LoggingEventTemplate.cshtml"
 if (Model.HttpContextInformation != null) {

            
            #line default
            #line hidden
WriteLiteral("    <h2>Request</h2>\r\n");


            
            #line 23 "..\..\Core\LoggingEventTemplate.cshtml"
    
            
            #line default
            #line hidden
            
            #line 23 "..\..\Core\LoggingEventTemplate.cshtml"
Write(WriteTable(Model.RequestSection));

            
            #line default
            #line hidden
            
            #line 23 "..\..\Core\LoggingEventTemplate.cshtml"
                                     
      
    if (Model.HttpContextInformation.RouteValues != null) {

            
            #line default
            #line hidden
WriteLiteral("        <h2>Route Values</h2>\r\n");


            
            #line 27 "..\..\Core\LoggingEventTemplate.cshtml"
        
            
            #line default
            #line hidden
            
            #line 27 "..\..\Core\LoggingEventTemplate.cshtml"
   Write(WriteTable(Model.HttpContextInformation.RouteValues));

            
            #line default
            #line hidden
            
            #line 27 "..\..\Core\LoggingEventTemplate.cshtml"
                                                             
    }
     
    if (Model.HttpContextInformation.QueryString != null) {

            
            #line default
            #line hidden
WriteLiteral("        <h2>QueryString</h2>\r\n");


            
            #line 32 "..\..\Core\LoggingEventTemplate.cshtml"
        
            
            #line default
            #line hidden
            
            #line 32 "..\..\Core\LoggingEventTemplate.cshtml"
   Write(WriteTable(Model.HttpContextInformation.QueryString));

            
            #line default
            #line hidden
            
            #line 32 "..\..\Core\LoggingEventTemplate.cshtml"
                                                             
    }
        
    if (Model.HttpContextInformation.PostedValues != null) {

            
            #line default
            #line hidden
WriteLiteral("        <h2>Posted Values</h2>\r\n");


            
            #line 37 "..\..\Core\LoggingEventTemplate.cshtml"
        
            
            #line default
            #line hidden
            
            #line 37 "..\..\Core\LoggingEventTemplate.cshtml"
   Write(WriteTable(Model.HttpContextInformation.PostedValues));

            
            #line default
            #line hidden
            
            #line 37 "..\..\Core\LoggingEventTemplate.cshtml"
                                                              
    }
        
    if (Model.HttpContextInformation.PostedFiles != null) {

            
            #line default
            #line hidden
WriteLiteral("        <h2>Posted Files</h2>\r\n");



WriteLiteral("        <table cellpadding=\"0\" cellspacing=\"0\">\r\n            <tr>\r\n              " +
"  <th class=\"first-col\" align=\"left\">Name</th>\r\n                <th align=\"left\"" +
">Content Type</th>\r\n                <th align=\"left\">Size</th>\r\n            </tr" +
">\r\n");


            
            #line 48 "..\..\Core\LoggingEventTemplate.cshtml"
               var i = 0;  

            
            #line default
            #line hidden

            
            #line 49 "..\..\Core\LoggingEventTemplate.cshtml"
             foreach (var postedFile in Model.HttpContextInformation.PostedFiles) {
                var classAtt = i % 2 > 0 ? "class=\"alt\"" : string.Empty;

            
            #line default
            #line hidden
WriteLiteral("                <tr ");


            
            #line 51 "..\..\Core\LoggingEventTemplate.cshtml"
               Write(classAtt);

            
            #line default
            #line hidden
WriteLiteral(">\r\n                    <td class=\"first-col\">");


            
            #line 52 "..\..\Core\LoggingEventTemplate.cshtml"
                                     Write(postedFile.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");


            
            #line 53 "..\..\Core\LoggingEventTemplate.cshtml"
                   Write(postedFile.ContentType);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");


            
            #line 54 "..\..\Core\LoggingEventTemplate.cshtml"
                   Write(FileSizeFormatProvider.FileSize(postedFile.ContentLength));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n");


            
            #line 56 "..\..\Core\LoggingEventTemplate.cshtml"
                i++;
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n");


            
            #line 59 "..\..\Core\LoggingEventTemplate.cshtml"
    }
        
    if (Model.HttpContextInformation.Cookies != null) {

            
            #line default
            #line hidden
WriteLiteral("        <h2>Cookies</h2>\r\n");


            
            #line 63 "..\..\Core\LoggingEventTemplate.cshtml"
        
            
            #line default
            #line hidden
            
            #line 63 "..\..\Core\LoggingEventTemplate.cshtml"
   Write(WriteTable(Model.HttpContextInformation.Cookies));

            
            #line default
            #line hidden
            
            #line 63 "..\..\Core\LoggingEventTemplate.cshtml"
                                                         
    }
        
    if (Model.HttpContextInformation.Headers != null) {

            
            #line default
            #line hidden
WriteLiteral("        <h2>Headers</h2>\r\n");


            
            #line 68 "..\..\Core\LoggingEventTemplate.cshtml"
        
            
            #line default
            #line hidden
            
            #line 68 "..\..\Core\LoggingEventTemplate.cshtml"
   Write(WriteTable(Model.HttpContextInformation.Headers));

            
            #line default
            #line hidden
            
            #line 68 "..\..\Core\LoggingEventTemplate.cshtml"
                                                         
    }
        
    if (Model.HttpContextInformation.ServerVariables != null) {

            
            #line default
            #line hidden
WriteLiteral("        <h2>Server Variables</h2>\r\n");


            
            #line 73 "..\..\Core\LoggingEventTemplate.cshtml"
        
            
            #line default
            #line hidden
            
            #line 73 "..\..\Core\LoggingEventTemplate.cshtml"
   Write(WriteTable(Model.HttpContextInformation.ServerVariables));

            
            #line default
            #line hidden
            
            #line 73 "..\..\Core\LoggingEventTemplate.cshtml"
                                                                 
    }
        
    if (Model.HttpContextInformation.Session != null) {

            
            #line default
            #line hidden
WriteLiteral("        <h2>Session Variables</h2>\r\n");


            
            #line 78 "..\..\Core\LoggingEventTemplate.cshtml"
        
            
            #line default
            #line hidden
            
            #line 78 "..\..\Core\LoggingEventTemplate.cshtml"
   Write(WriteTable(Model.HttpContextInformation.Session));

            
            #line default
            #line hidden
            
            #line 78 "..\..\Core\LoggingEventTemplate.cshtml"
                                                         
    }
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 82 "..\..\Core\LoggingEventTemplate.cshtml"
 if (Model.ExceptionInformation != null) {

            
            #line default
            #line hidden
WriteLiteral("    <h2>Exception</h2>\r\n");



WriteLiteral("    <table cellpadding=\"0\" cellspacing=\"0\">\r\n        <tr>\r\n            <td class=" +
"\"first-col\">Message</td>\r\n            <td>");


            
            #line 87 "..\..\Core\LoggingEventTemplate.cshtml"
           Write(Model.ExceptionInformation.Message);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n        </tr>\r\n        <tr class=\"alt\">\r\n            <td class=\"first-col\"" +
">Type</td>\r\n            <td>");


            
            #line 91 "..\..\Core\LoggingEventTemplate.cshtml"
           Write(Model.ExceptionInformation.Type);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n        </tr>\r\n        <tr>\r\n            <td class=\"first-col\">Source</td>" +
"\r\n            <td>");


            
            #line 95 "..\..\Core\LoggingEventTemplate.cshtml"
           Write(Model.ExceptionInformation.Source);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n        </tr>\r\n        <tr class=\"alt\">\r\n            <td class=\"first-col\"" +
">StatusCode</td>\r\n            <td>");


            
            #line 99 "..\..\Core\LoggingEventTemplate.cshtml"
           Write(Model.ExceptionInformation.StatusCode);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n        </tr>\r\n    </table>\r\n");


            
            #line 102 "..\..\Core\LoggingEventTemplate.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("    \r\n");


            
            #line 104 "..\..\Core\LoggingEventTemplate.cshtml"
 if (Model.StackTrace != null) {

            
            #line default
            #line hidden
WriteLiteral("    <h2>StackTrace</h2>\r\n");



WriteLiteral("    <pre class=\"stacktrace\">");


            
            #line 106 "..\..\Core\LoggingEventTemplate.cshtml"
                       Write(Model.StackTrace);

            
            #line default
            #line hidden
WriteLiteral("</pre>\r\n");


            
            #line 107 "..\..\Core\LoggingEventTemplate.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("    \r\n");


            
            #line 109 "..\..\Core\LoggingEventTemplate.cshtml"
 if (Model.SqlInformation != null) {

            
            #line default
            #line hidden
WriteLiteral("    <h2>SQL</h2>\r\n");


            
            #line 111 "..\..\Core\LoggingEventTemplate.cshtml"
    
            
            #line default
            #line hidden
            
            #line 111 "..\..\Core\LoggingEventTemplate.cshtml"
Write(WriteTable(ObjectHelpers.ToDictionary(Model.SqlInformation.Parameters)));

            
            #line default
            #line hidden
            
            #line 111 "..\..\Core\LoggingEventTemplate.cshtml"
                                                                            

            
            #line default
            #line hidden
WriteLiteral("    <pre class=\"sql\">");


            
            #line 112 "..\..\Core\LoggingEventTemplate.cshtml"
                Write(Model.SqlInformation.SQL);

            
            #line default
            #line hidden
WriteLiteral("</pre>\r\n");


            
            #line 113 "..\..\Core\LoggingEventTemplate.cshtml"
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
