#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pulsus.Internal
{
    using System;
    using System.Collections.Generic;
    
    #line 2 "..\..\Internal\EmailTemplate.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 3 "..\..\Internal\EmailTemplate.cshtml"
    using Internal;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    internal partial class EmailTemplate : RazorTemplateBase<EmailTemplateModel>
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");




WriteLiteral("<html>\r\n<head>\r\n    <meta charset=\"utf-8\" />\r\n\t<title>");


            
            #line 8 "..\..\Internal\EmailTemplate.cshtml"
   Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral(@"</title>
	<style type=""text/css""><!--
        body { font-family:""Segoe UI"",Verdana,arial,sans-serif;font-size:8pt;color:#444;padding:5px;background-color:#fff; }
        pre { display:block;width:100%;font-family:Consolas,""Courier New"";background:#f4f4f4;border:1px solid #999;padding:10px;word-break:break-all;word-wrap:break-word;display:block; }
		h1,h2,h3 { font-family:""Segoe UI"",Verdana,arial,sans-serif;color:#666; }
		h1 { font-size:18pt; }
        h2 { font-size:10pt;margin:10px 4px 5px 4px; }
		table { display:table;width:100%;border:1px solid #999;width:100%;table-layout:fixed; }
		table th { background:#333;color:#fff;padding:5px;min-width:100px;text-align:left; }
		table td { padding:5px;word-break:break-all; }
        table td.first-col { word-break:normal;word-wrap:normal; }
        table tr.alt td { background-color:#f4f4f4; }
        table.title { border:0; }
        table.title td.level { width:8px; }
        table.title td.red { background-color:#ff2727; }
        table.title td.yellow { background-color:#ffcb00; }
        table.title td.green { background-color:#008e1d; }
        table.title td.blue { background-color:#1f2aef; }
        table.title td { padding-left:12px; }
        table.title h1 { color:#444; }
        a.link, a.link:hover, a.link:visited { color:#444; }
	--></style>
</head>
	<body>
		<table cellpadding=""0"" cellspacing=""0"" class=""title"">
			<tr>
				<td width=""8"" style="""" class=""first-col level ");


            
            #line 34 "..\..\Internal\EmailTemplate.cshtml"
                                             Write(Model.LevelClass);

            
            #line default
            #line hidden
WriteLiteral("\">&nbsp;</td>\r\n\t\t\t\t<td>\r\n\t\t\t\t\t<h1>\r\n");


            
            #line 37 "..\..\Internal\EmailTemplate.cshtml"
 						if (Model.Link != null) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t<a class=\"link\" href=\"");


            
            #line 38 "..\..\Internal\EmailTemplate.cshtml"
                        Write(Model.Link);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 38 "..\..\Internal\EmailTemplate.cshtml"
                                     Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");


            
            #line 39 "..\..\Internal\EmailTemplate.cshtml"
						} else {
							
            
            #line default
            #line hidden
            
            #line 40 "..\..\Internal\EmailTemplate.cshtml"
  Write(Model.Title);

            
            #line default
            #line hidden
            
            #line 40 "..\..\Internal\EmailTemplate.cshtml"
                   
						}

            
            #line default
            #line hidden
WriteLiteral(@"					</h1>
				</td>
			</tr>
		</table>
    
		<h2>General</h2>
		<table cellpadding=""0"" cellspacing=""0"">
			<tr>
				<th class=""first-col"" align=""left"">Key</th>
				<th align=""left"">Value</th>
			</tr>
			<tr>
				<td class=""first-col"">Date</td>
				<td>");


            
            #line 55 "..\..\Internal\EmailTemplate.cshtml"
   Write(Model.LoggingEvent.Date);

            
            #line default
            #line hidden
WriteLiteral(" UTC</td>\r\n\t\t\t</tr>\r\n            <tr class=\"alt\">\r\n\t\t\t\t<td class=\"first-col\">ID</" +
"td>\r\n\t\t\t\t<td>");


            
            #line 59 "..\..\Internal\EmailTemplate.cshtml"
   Write(Model.LoggingEvent.EventId);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td class=\"first-col\">Level</td>\r\n\t\t\t\t<td>");


            
            #line 63 "..\..\Internal\EmailTemplate.cshtml"
   Write(Model.LevelText);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr class=\"alt\">\r\n\t\t\t\t<td class=\"first-col\">User</td>\r\n\t\t\t\t<t" +
"d>");


            
            #line 67 "..\..\Internal\EmailTemplate.cshtml"
    Write(Model.LoggingEvent.User ?? "&nbsp;");

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td class=\"first-col\">Tags</td>\r\n\t\t\t\t<td>");


            
            #line 71 "..\..\Internal\EmailTemplate.cshtml"
   Write(string.Join(" ", Model.LoggingEvent.Tags.ToArray()));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr class=\"alt\">\r\n\t\t\t\t<td class=\"first-col\">MachineName</td>\r" +
"\n\t\t\t\t<td>");


            
            #line 75 "..\..\Internal\EmailTemplate.cshtml"
   Write(Model.LoggingEvent.MachineName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t</tr>\r\n\t\t</table>\r\n        \r\n");


            
            #line 79 "..\..\Internal\EmailTemplate.cshtml"
         if (Model.CustomData != null) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<h2>Custom Data</h2>\r\n");


            
            #line 81 "..\..\Internal\EmailTemplate.cshtml"
            
            
            #line default
            #line hidden
            
            #line 81 "..\..\Internal\EmailTemplate.cshtml"
       Write(WriteTable(Model.CustomData));

            
            #line default
            #line hidden
            
            #line 81 "..\..\Internal\EmailTemplate.cshtml"
                                         
		}

            
            #line default
            #line hidden
WriteLiteral("    \r\n");


            
            #line 84 "..\..\Internal\EmailTemplate.cshtml"
 		if (Model.HttpContextInformation != null) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<h2>Request</h2>\r\n");



WriteLiteral("\t\t\t<table cellpadding=\"0\" cellspacing=\"0\">\r\n\t\t\t\t<tr>\r\n\t\t\t\t\t<th class=\"first-col\" " +
"align=\"left\">Key</th>\r\n\t\t\t\t\t<th align=\"left\">Value</th>\r\n\t\t\t\t</tr>\r\n\t\t\t\t<tr>\r\n\t\t" +
"\t\t\t<td class=\"first-col\">URL</td>\r\n\t\t\t\t\t<td>");


            
            #line 93 "..\..\Internal\EmailTemplate.cshtml"
    Write(Model.HttpContextInformation.Url);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t\t</tr>\r\n\t\t\t\t<tr class=\"alt\">\r\n\t\t\t\t\t<td class=\"first-col\">Method</td>\r\n\t" +
"\t\t\t\t<td>");


            
            #line 97 "..\..\Internal\EmailTemplate.cshtml"
    Write(Model.HttpContextInformation.Method);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t\t</tr>\r\n\t\t\t\t<tr>\r\n\t\t\t\t\t<td class=\"first-col\">Host</td>\r\n\t\t\t\t\t<td>");


            
            #line 101 "..\..\Internal\EmailTemplate.cshtml"
    Write(Model.HttpContextInformation.Host);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t\t</tr>\r\n\t\t\t\t<tr class=\"alt\">\r\n\t\t\t\t\t<td class=\"first-col\">Referer</td>\r\n" +
"\t\t\t\t\t<td>");


            
            #line 105 "..\..\Internal\EmailTemplate.cshtml"
    Write(Model.HttpContextInformation.Referer);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t\t</tr>\r\n\t\t\t\t<tr>\r\n\t\t\t\t\t<td class=\"first-col\">Method</td>\r\n\t\t\t\t\t<td>");


            
            #line 109 "..\..\Internal\EmailTemplate.cshtml"
    Write(Model.HttpContextInformation.Method);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t\t</tr>\r\n\t\t\t\t<tr class=\"alt\">\r\n\t\t\t\t\t<td class=\"first-col\">IP Address</td" +
">\r\n\t\t\t\t\t<td>");


            
            #line 113 "..\..\Internal\EmailTemplate.cshtml"
    Write(Model.HttpContextInformation.IpAddress);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t\t</tr>\r\n\t\t\t\t<tr>\r\n\t\t\t\t\t<td class=\"first-col\">User Agent</td>\r\n\t\t\t\t\t<td>" +
"");


            
            #line 117 "..\..\Internal\EmailTemplate.cshtml"
    Write(Model.HttpContextInformation.UserAgent);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t\t</tr>\r\n\t\t\t</table>\r\n");


            
            #line 120 "..\..\Internal\EmailTemplate.cshtml"
      
            if (Model.HttpContextInformation.RouteValues != null) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t<h2>Route Values</h2>\r\n");


            
            #line 123 "..\..\Internal\EmailTemplate.cshtml"
				
            
            #line default
            #line hidden
            
            #line 123 "..\..\Internal\EmailTemplate.cshtml"
Write(WriteTable(Model.HttpContextInformation.RouteValues));

            
            #line default
            #line hidden
            
            #line 123 "..\..\Internal\EmailTemplate.cshtml"
                                                         
			}
     
			if (Model.HttpContextInformation.QueryString != null) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t<h2>QueryString</h2>\r\n");


            
            #line 128 "..\..\Internal\EmailTemplate.cshtml"
				
            
            #line default
            #line hidden
            
            #line 128 "..\..\Internal\EmailTemplate.cshtml"
Write(WriteTable(Model.HttpContextInformation.QueryString));

            
            #line default
            #line hidden
            
            #line 128 "..\..\Internal\EmailTemplate.cshtml"
                                                         
			}
        
			if (Model.HttpContextInformation.PostedValues != null) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t<h2>Posted Values</h2>\r\n");


            
            #line 133 "..\..\Internal\EmailTemplate.cshtml"
				
            
            #line default
            #line hidden
            
            #line 133 "..\..\Internal\EmailTemplate.cshtml"
Write(WriteTable(Model.HttpContextInformation.PostedValues));

            
            #line default
            #line hidden
            
            #line 133 "..\..\Internal\EmailTemplate.cshtml"
                                                          
			}
        
		    if (Model.HttpContextInformation.PostedFiles != null) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t<h2>Posted Files</h2>\r\n");



WriteLiteral("\t\t\t\t<table cellpadding=\"0\" cellspacing=\"0\">\r\n\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t<th class=\"first-co" +
"l\" align=\"left\">Name</th>\r\n\t\t\t\t\t\t<th align=\"left\">Content Type</th>\r\n\t\t\t\t\t\t<th a" +
"lign=\"left\">Size</th>\r\n\t\t\t\t\t</tr>\r\n");


            
            #line 144 "..\..\Internal\EmailTemplate.cshtml"
                       var i = 0;  

            
            #line default
            #line hidden

            
            #line 145 "..\..\Internal\EmailTemplate.cshtml"
                     foreach (var postedFile in Model.HttpContextInformation.PostedFiles) {
                        var classAtt = i % 2 > 0 ? "class=\"alt\"" : string.Empty;

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t<tr ");


            
            #line 147 "..\..\Internal\EmailTemplate.cshtml"
     Write(classAtt);

            
            #line default
            #line hidden
WriteLiteral(">\r\n\t\t\t\t\t\t\t<td class=\"first-col\">");


            
            #line 148 "..\..\Internal\EmailTemplate.cshtml"
                        Write(postedFile.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t\t\t\t\t<td>");


            
            #line 149 "..\..\Internal\EmailTemplate.cshtml"
      Write(postedFile.ContentType);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t\t\t\t\t<td>");


            
            #line 150 "..\..\Internal\EmailTemplate.cshtml"
      Write(FileSizeFormatProvider.FileSize(postedFile.ContentLength));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t\t\t\t</tr>\r\n");


            
            #line 152 "..\..\Internal\EmailTemplate.cshtml"
                        i++;
					}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t</table>\r\n");


            
            #line 155 "..\..\Internal\EmailTemplate.cshtml"
		    }
        
			if (Model.HttpContextInformation.Cookies != null) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t<h2>Cookies</h2>\r\n");


            
            #line 159 "..\..\Internal\EmailTemplate.cshtml"
				
            
            #line default
            #line hidden
            
            #line 159 "..\..\Internal\EmailTemplate.cshtml"
Write(WriteTable(Model.HttpContextInformation.Cookies));

            
            #line default
            #line hidden
            
            #line 159 "..\..\Internal\EmailTemplate.cshtml"
                                                     
			}
        
			if (Model.HttpContextInformation.Headers != null) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t<h2>Headers</h2>\r\n");


            
            #line 164 "..\..\Internal\EmailTemplate.cshtml"
				
            
            #line default
            #line hidden
            
            #line 164 "..\..\Internal\EmailTemplate.cshtml"
Write(WriteTable(Model.HttpContextInformation.Headers));

            
            #line default
            #line hidden
            
            #line 164 "..\..\Internal\EmailTemplate.cshtml"
                                                     
			}
        
			if (Model.HttpContextInformation.ServerVariables != null) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t<h2>Server Variables</h2>\r\n");


            
            #line 169 "..\..\Internal\EmailTemplate.cshtml"
				
            
            #line default
            #line hidden
            
            #line 169 "..\..\Internal\EmailTemplate.cshtml"
Write(WriteTable(Model.HttpContextInformation.ServerVariables));

            
            #line default
            #line hidden
            
            #line 169 "..\..\Internal\EmailTemplate.cshtml"
                                                             
			}
        
			if (Model.HttpContextInformation.Session != null) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t<h2>Session Variables</h2>\r\n");


            
            #line 174 "..\..\Internal\EmailTemplate.cshtml"
				
            
            #line default
            #line hidden
            
            #line 174 "..\..\Internal\EmailTemplate.cshtml"
Write(WriteTable(Model.HttpContextInformation.Session));

            
            #line default
            #line hidden
            
            #line 174 "..\..\Internal\EmailTemplate.cshtml"
                                                     
			}
		}

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 178 "..\..\Internal\EmailTemplate.cshtml"
 		if (Model.ExceptionInformation != null) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<h2>Exception</h2>\r\n");



WriteLiteral("\t\t\t<table cellpadding=\"0\" cellspacing=\"0\">\r\n\t\t\t\t<tr>\r\n\t\t\t\t\t<th class=\"first-col\" " +
"align=\"left\">Key</th>\r\n\t\t\t\t\t<th align=\"left\">Value</th>\r\n\t\t\t\t</tr>\r\n\t\t\t\t<tr>\r\n\t\t" +
"\t\t\t<td class=\"first-col\">Message</td>\r\n\t\t\t\t\t<td>");


            
            #line 187 "..\..\Internal\EmailTemplate.cshtml"
    Write(Model.ExceptionInformation.Message);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t\t</tr>\r\n\t\t\t\t<tr class=\"alt\">\r\n\t\t\t\t\t<td class=\"first-col\">Type</td>\r\n\t\t\t" +
"\t\t<td>");


            
            #line 191 "..\..\Internal\EmailTemplate.cshtml"
    Write(Model.ExceptionInformation.Type);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t\t</tr>\r\n\t\t\t\t<tr>\r\n\t\t\t\t\t<td class=\"first-col\">Source</td>\r\n\t\t\t\t\t<td>");


            
            #line 195 "..\..\Internal\EmailTemplate.cshtml"
    Write(Model.ExceptionInformation.Source);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t\t</tr>\r\n\t\t\t\t<tr class=\"alt\">\r\n\t\t\t\t\t<td class=\"first-col\">StatusCode</td" +
">\r\n\t\t\t\t\t<td>");


            
            #line 199 "..\..\Internal\EmailTemplate.cshtml"
    Write(Model.ExceptionInformation.StatusCode);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t\t</tr>\r\n\t\t\t</table>\r\n");


            
            #line 202 "..\..\Internal\EmailTemplate.cshtml"
		}

            
            #line default
            #line hidden
WriteLiteral("    \r\n");


            
            #line 204 "..\..\Internal\EmailTemplate.cshtml"
 		if (Model.StackTrace != null) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<h2>StackTrace</h2>\r\n");



WriteLiteral("\t\t\t<pre class=\"stacktrace\">");


            
            #line 206 "..\..\Internal\EmailTemplate.cshtml"
                      Write(Model.StackTrace);

            
            #line default
            #line hidden
WriteLiteral("</pre>\r\n");


            
            #line 207 "..\..\Internal\EmailTemplate.cshtml"
		}

            
            #line default
            #line hidden
WriteLiteral("    \r\n");


            
            #line 209 "..\..\Internal\EmailTemplate.cshtml"
 		if (Model.SqlInformation != null) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<h2>SQL</h2>\r\n");


            
            #line 211 "..\..\Internal\EmailTemplate.cshtml"
			
            
            #line default
            #line hidden
            
            #line 211 "..\..\Internal\EmailTemplate.cshtml"
Write(WriteTable(Model.SqlInformation.Parameters));

            
            #line default
            #line hidden
            
            #line 211 "..\..\Internal\EmailTemplate.cshtml"
                                               

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<pre class=\"sql\">");


            
            #line 212 "..\..\Internal\EmailTemplate.cshtml"
               Write(Model.SqlInformation.SQL);

            
            #line default
            #line hidden
WriteLiteral("</pre>\r\n");


            
            #line 213 "..\..\Internal\EmailTemplate.cshtml"
		}

            
            #line default
            #line hidden
WriteLiteral("        <br />\r\n        ");


            
            #line 215 "..\..\Internal\EmailTemplate.cshtml"
   Write(Model.Footer);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t</body>\r\n</html>");


        }
    }
}
#pragma warning restore 1591
